### ISSUE TITLE
Add binding for aimbot

### ISSUE THREAD

**Issue by Dmajster** [pecarprimoz/cs2cfg-peco#1]
in cs2_user_keys_0_slot0.vcfg

"0"		"\<unbound\>"

should be changed to 

"0"		"toggle sv_aimbot"

**Comment by pecarprimoz** [comment]
<img width="121" alt="Screenshot 2024-02-29 173931" src="https://github.com/pecarprimoz/cs2cfg-peco/assets/22977534/e9376c56-aa51-4b72-bcf1-6e10b03378c1">
